export const DB_PROVIDER = 'BOFANS_DATA_SOURCE';
export const DB_PROVIDES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  PHOTO_REPOSITORY: 'PHOTO_REPOSITORY',
  PHOTO_VOTE_REPOSITORY: 'PHOTO_VOTE_REPOSITORY',
  KOWTOW_REPOSITORY: 'KOWTOW_REPOSITORY',
};
